// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wukna.Shared.Data.AppDbContext;

#nullable disable

namespace Wukna.Migrations
{
    [DbContext(typeof(WuknaDbContext))]
    [Migration("20261003214259_AddChatTaskCalendarImports")]
    partial class AddChatTaskCalendarImports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Auth.ExternalLoginGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrowserBindingHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("browser_binding_hash");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_login_grants");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_external_login_grants_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_external_login_grants_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_login_grants_user_id");

                    b.ToTable("external_login_grants", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_user_id_is_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Board.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_boards");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_boards_title");

                    b.ToTable("boards", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Board.BoardMembership", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("BoardId", "UserId")
                        .HasName("pk_board_memberships");

                    b.HasIndex("BoardId")
                        .IsUnique()
                        .HasDatabaseName("ix_board_memberships_board_id")
                        .HasFilter("\"role\" = 1");

                    b.HasIndex("UserId", "BoardId")
                        .HasDatabaseName("ix_board_memberships_user_id_board_id");

                    b.ToTable("board_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_membership_owner_can_edit", "\"role\" <> 1 OR \"can_edit\"");

                            t.HasCheckConstraint("ck_board_membership_role", "\"role\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Calendar.CalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AllDayEndDateExclusive")
                        .HasColumnType("date")
                        .HasColumnName("all_day_end_date_exclusive");

                    b.Property<DateOnly?>("AllDayStartDate")
                        .HasColumnType("date")
                        .HasColumnName("all_day_start_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<DateTime?>("LocalEnd")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("local_end");

                    b.Property<DateTime?>("LocalStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("local_start");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid?>("SourceChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_chat_message_id");

                    b.Property<DateTimeOffset?>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_events");

                    b.HasIndex("UserId", "SourceChatMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_calendar_events_user_id_source_chat_message_id")
                        .HasFilter("source_chat_message_id IS NOT NULL");

                    b.HasIndex("UserId", "AllDayStartDate", "AllDayEndDateExclusive")
                        .HasDatabaseName("ix_calendar_events_user_id_all_day_start_date_all_day_end_date");

                    b.HasIndex("UserId", "StartAtUtc", "EndAtUtc")
                        .HasDatabaseName("ix_calendar_events_user_id_start_at_utc_end_at_utc");

                    b.ToTable("calendar_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_event_schedule", "(is_all_day AND all_day_start_date IS NOT NULL AND all_day_end_date_exclusive IS NOT NULL AND all_day_end_date_exclusive > all_day_start_date AND local_start IS NULL AND local_end IS NULL AND time_zone_id IS NULL AND start_at_utc IS NULL AND end_at_utc IS NULL) OR (NOT is_all_day AND all_day_start_date IS NULL AND all_day_end_date_exclusive IS NULL AND local_start IS NOT NULL AND time_zone_id IS NOT NULL AND start_at_utc IS NOT NULL AND ((source_chat_message_id IS NULL AND local_end IS NOT NULL AND local_end > local_start AND end_at_utc IS NOT NULL AND end_at_utc > start_at_utc) OR (source_chat_message_id IS NOT NULL AND ((local_end IS NULL AND end_at_utc IS NULL) OR (local_end IS NOT NULL AND end_at_utc IS NOT NULL AND end_at_utc > start_at_utc)))))");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.BoardChatSettings", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<long>("LastMessageSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_message_sequence");

                    b.Property<long>("SettingsRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("settings_revision");

                    b.Property<int>("SlowModeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("slow_mode_seconds");

                    b.HasKey("BoardId")
                        .HasName("pk_board_chat_settings");

                    b.ToTable("board_chat_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_chat_settings_cooldown", "slow_mode_seconds BETWEEN 0 AND 21600");

                            t.HasCheckConstraint("ck_board_chat_settings_counters", "settings_revision > 0 AND last_message_sequence >= 0");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.BoardMemberChatState", b =>
                {
                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("CooldownSettingsRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("cooldown_settings_revision");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<long>("LastReadSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_sequence");

                    b.Property<Guid>("MembershipInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_instance_id");

                    b.Property<long>("ModerationRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("moderation_revision");

                    b.Property<DateTimeOffset?>("MutedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("muted_until");

                    b.Property<DateTimeOffset?>("NextSendAllowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_send_allowed_at");

                    b.HasKey("BoardId", "UserId")
                        .HasName("pk_board_member_chat_states");

                    b.ToTable("board_member_chat_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_member_chat_state_counters", "moderation_revision >= 0 AND cooldown_settings_revision >= 0 AND last_read_sequence >= 0");

                            t.HasCheckConstraint("ck_board_member_chat_state_instance", "membership_instance_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_board_member_chat_state_mute", "is_muted OR muted_until IS NULL");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<long>("InputByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("input_byte_size");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("NextScanAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_scan_attempt_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OriginalStorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_storage_key");

                    b.Property<long>("PreviewByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("preview_byte_size");

                    b.Property<string>("PreviewStorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("preview_storage_key");

                    b.Property<int>("ScanAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("scan_attempts");

                    b.Property<DateTimeOffset?>("ScanLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scan_lease_expires_at");

                    b.Property<Guid?>("ScanLeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_lease_token");

                    b.Property<int>("ScanStatus")
                        .HasColumnType("integer")
                        .HasColumnName("scan_status");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_key");

                    b.Property<long>("StoredByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("stored_byte_size");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_chat_attachments");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_attachments_message_id");

                    b.HasIndex("NextScanAttemptAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_chat_attachments_scan_work")
                        .HasFilter("scan_status IN (0, 1, 4)");

                    b.ToTable("chat_attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_attachment_attempts", "scan_attempts >= 0");

                            t.HasCheckConstraint("ck_chat_attachment_available_scan", "scan_status <> 2 OR scanned_at IS NOT NULL");

                            t.HasCheckConstraint("ck_chat_attachment_dimensions", "width > 0 AND height > 0");

                            t.HasCheckConstraint("ck_chat_attachment_lease", "(scan_status = 1 AND scan_lease_token IS NOT NULL AND scan_lease_expires_at IS NOT NULL) OR (scan_status <> 1 AND scan_lease_token IS NULL AND scan_lease_expires_at IS NULL)");

                            t.HasCheckConstraint("ck_chat_attachment_sizes", "input_byte_size > 0 AND byte_size > 0 AND preview_byte_size > 0 AND stored_byte_size >= byte_size + preview_byte_size");

                            t.HasCheckConstraint("ck_chat_attachment_status", "scan_status IN (0, 1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatBlobWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<Guid?>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<string>("OriginalStorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("original_storage_key");

                    b.Property<string>("PreviewStorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("preview_storage_key");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<long>("ReservedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_blob_work");

                    b.HasIndex("DueAt", "Id")
                        .HasDatabaseName("ix_chat_blob_work_due_at_id");

                    b.HasIndex("BoardId", "UserId", "ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_blob_work_upload_reservation")
                        .HasFilter("purpose = 0");

                    b.ToTable("chat_blob_work", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_blob_work_counters", "reserved_bytes >= 0 AND attempts >= 0");

                            t.HasCheckConstraint("ck_chat_blob_work_lease", "(lease_token IS NULL AND lease_expires_at IS NULL) OR (lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_chat_blob_work_purpose", "purpose IN (0, 1)");

                            t.HasCheckConstraint("ck_chat_blob_work_reservation", "purpose <> 0 OR (user_id IS NOT NULL AND client_message_id IS NOT NULL AND reserved_bytes > 0)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<string>("Body")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SenderUserId")
                        .HasDatabaseName("ix_chat_messages_sender_user_id");

                    b.HasIndex("BoardId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_messages_board_id_sequence");

                    b.HasIndex("BoardId", "SenderUserId", "ClientMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_messages_board_id_sender_user_id_client_message_id");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_message_body", "(type = 0 AND body IS NOT NULL AND length(btrim(body)) BETWEEN 1 AND 4000) OR (type = 1 AND (body IS NULL OR length(body) <= 2000)) OR (type = 2 AND body IS NULL)");

                            t.HasCheckConstraint("ck_chat_message_client_id", "client_message_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_chat_message_fingerprint", "request_fingerprint ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_chat_message_sequence", "sequence > 0");

                            t.HasCheckConstraint("ck_chat_message_type", "type IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<Guid?>("MemberUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_user_id");

                    b.Property<Guid?>("MembershipInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_instance_id");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<long?>("MessageSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("message_sequence");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long?>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_chat_outbox_events");

                    b.HasIndex("NextAttemptAt", "CreatedAt", "Id")
                        .HasDatabaseName("ix_chat_outbox_events_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("chat_outbox_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_outbox_counters", "event_version > 0 AND attempts >= 0 AND (revision IS NULL OR revision >= 0) AND (message_sequence IS NULL OR message_sequence >= 0)");

                            t.HasCheckConstraint("ck_chat_outbox_kind", "kind IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("ck_chat_outbox_lease", "(lease_token IS NULL AND lease_expires_at IS NULL) OR (lease_token IS NOT NULL AND lease_expires_at IS NOT NULL AND processed_at IS NULL)");

                            t.HasCheckConstraint("ck_chat_outbox_payload", "(kind = 0 AND message_id IS NOT NULL AND message_sequence IS NOT NULL AND message_sequence > 0) OR (kind = 1 AND revision IS NOT NULL) OR (kind = 2 AND member_user_id IS NOT NULL AND revision IS NOT NULL) OR (kind = 3 AND attachment_id IS NOT NULL AND message_id IS NOT NULL) OR (kind = 4 AND member_user_id IS NOT NULL AND message_sequence IS NOT NULL) OR (kind = 5 AND ((member_user_id IS NULL AND membership_instance_id IS NULL) OR (member_user_id IS NOT NULL AND membership_instance_id IS NOT NULL)))");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Chat.ScheduledChatTask", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<int>("OriginalOffsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("original_offset_minutes");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("MessageId")
                        .HasName("pk_scheduled_chat_tasks");

                    b.ToTable("scheduled_chat_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_scheduled_chat_task_end", "ends_at_utc IS NULL OR ends_at_utc > starts_at_utc");

                            t.HasCheckConstraint("ck_scheduled_chat_task_offset", "original_offset_minutes BETWEEN -840 AND 840");

                            t.HasCheckConstraint("ck_scheduled_chat_task_title", "length(btrim(title)) > 0");

                            t.HasCheckConstraint("ck_scheduled_chat_task_zone", "length(btrim(time_zone_id)) > 0");
                        });
                });

            modelBuilder.Entity("Wukna.Features.NoteConnection.NoteConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_type");

                    b.Property<string>("SourceHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_handle");

                    b.Property<Guid>("SourceNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_note_id");

                    b.Property<string>("TargetHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_handle");

                    b.Property<Guid>("TargetNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_note_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_note_connections");

                    b.HasIndex("BoardId", "SourceNoteId")
                        .HasDatabaseName("ix_note_connections_board_id_source_note_id");

                    b.HasIndex("BoardId", "TargetNoteId")
                        .HasDatabaseName("ix_note_connections_board_id_target_note_id");

                    b.ToTable("note_connections", null, t =>
                        {
                            t.HasCheckConstraint("ck_note_connection_type", "\"type\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Notes.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("Height")
                        .HasColumnType("double precision")
                        .HasColumnName("height");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_note_id");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<double>("Width")
                        .HasColumnType("double precision")
                        .HasColumnName("width");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasAlternateKey("BoardId", "Id")
                        .HasName("ak_notes_board_id_id");

                    b.HasIndex("BoardId", "Kind")
                        .HasDatabaseName("ix_notes_board_id_kind");

                    b.HasIndex("BoardId", "ParentNoteId")
                        .HasDatabaseName("ix_notes_board_id_parent_note_id")
                        .HasFilter("\"parent_note_id\" IS NOT NULL");

                    b.ToTable("notes", null, t =>
                        {
                            t.HasCheckConstraint("ck_note_color_hex", "\"color\" ~ '^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$'");

                            t.HasCheckConstraint("ck_note_dimensions_positive", "\"width\" > 0 AND \"height\" > 0");

                            t.HasCheckConstraint("ck_note_kind", "\"kind\" IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_note_parent_matches_kind", "(\"kind\" = 2 AND \"parent_note_id\" IS NOT NULL) OR (\"kind\" IN (0, 1) AND \"parent_note_id\" IS NULL)");

                            t.HasCheckConstraint("ck_note_position_matches_kind", "(\"kind\" = 2 AND \"position_x\" IS NULL AND \"position_y\" IS NULL) OR (\"kind\" IN (0, 1) AND \"position_x\" IS NOT NULL AND \"position_y\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Notifications.TaskNotification", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId")
                        .HasName("pk_task_notifications");

                    b.HasIndex("UserId", "IssuedAt")
                        .HasDatabaseName("ix_task_notifications_user_id_issued_at");

                    b.ToTable("task_notifications", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Notifications.TaskReminder", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<int>("MinutesBefore")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_before");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TaskId")
                        .HasName("pk_task_reminders");

                    b.HasIndex("DeliveredAt", "DueAtUtc")
                        .HasDatabaseName("ix_task_reminders_delivered_at_due_at_utc");

                    b.HasIndex("UserId", "DueAtUtc")
                        .HasDatabaseName("ix_task_reminders_user_id_due_at_utc");

                    b.ToTable("task_reminders", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_reminder_minutes", "minutes_before BETWEEN 0 AND 10080");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Tasks.PersonalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<DateTimeOffset?>("PlannedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at_utc");

                    b.Property<DateOnly?>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<TimeOnly?>("PlannedTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("planned_time");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_personal_tasks");

                    b.HasIndex("ListId")
                        .HasDatabaseName("ix_personal_tasks_list_id");

                    b.HasIndex("UserId", "ListId")
                        .HasDatabaseName("ix_personal_tasks_user_id_list_id");

                    b.HasIndex("UserId", "CompletedAt", "PlannedDate")
                        .HasDatabaseName("ix_personal_tasks_user_id_completed_at_planned_date");

                    b.ToTable("personal_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_personal_task_schedule", "(planned_time IS NULL AND time_zone_id IS NULL AND planned_at_utc IS NULL) OR (planned_date IS NOT NULL AND planned_time IS NOT NULL AND time_zone_id IS NOT NULL AND planned_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Wukna.Features.Tasks.PersonalTaskList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_personal_task_lists");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_personal_task_lists_user_name");

                    b.ToTable("personal_task_lists", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Tasks.PlanningSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("pk_planning_settings");

                    b.ToTable("planning_settings", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Tasks.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("items_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_task_templates");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_task_templates_user_id");

                    b.ToTable("task_templates", (string)null);
                });

            modelBuilder.Entity("Wukna.Features.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProfileImageKey")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("profile_image_key");

                    b.Property<string>("ProfileImageVersion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("profile_image_version");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_normalized_username");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Wukna.Features.Auth.ExternalLoginGrant", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_login_grants_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Auth.RefreshToken", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Board.BoardMembership", b =>
                {
                    b.HasOne("Wukna.Features.Board.Board", "Board")
                        .WithMany("Memberships")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_memberships_boards_board_id");

                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany("BoardMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_board_memberships_users_user_id");

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Calendar.CalendarEvent", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_events_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Chat.BoardChatSettings", b =>
                {
                    b.HasOne("Wukna.Features.Board.Board", "Board")
                        .WithOne()
                        .HasForeignKey("Wukna.Features.Chat.BoardChatSettings", "BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_chat_settings_boards_board_id");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Wukna.Features.Chat.BoardMemberChatState", b =>
                {
                    b.HasOne("Wukna.Features.Board.BoardMembership", "Membership")
                        .WithOne()
                        .HasForeignKey("Wukna.Features.Chat.BoardMemberChatState", "BoardId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_member_chat_states_board_memberships_board_id_user_id");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatAttachment", b =>
                {
                    b.HasOne("Wukna.Features.Chat.ChatMessage", "Message")
                        .WithOne("Attachment")
                        .HasForeignKey("Wukna.Features.Chat.ChatAttachment", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_attachments_chat_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatMessage", b =>
                {
                    b.HasOne("Wukna.Features.Board.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_boards_board_id");

                    b.HasOne("Wukna.Features.Users.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_users_sender_user_id");

                    b.Navigation("Board");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("Wukna.Features.Chat.ScheduledChatTask", b =>
                {
                    b.HasOne("Wukna.Features.Chat.ChatMessage", "Message")
                        .WithOne("ScheduledTask")
                        .HasForeignKey("Wukna.Features.Chat.ScheduledChatTask", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scheduled_chat_tasks_chat_messages_message_id");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Wukna.Features.NoteConnection.NoteConnection", b =>
                {
                    b.HasOne("Wukna.Features.Notes.Note", "SourceNote")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("BoardId", "SourceNoteId")
                        .HasPrincipalKey("BoardId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_connections_notes_board_id_source_note_id");

                    b.HasOne("Wukna.Features.Notes.Note", "TargetNote")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("BoardId", "TargetNoteId")
                        .HasPrincipalKey("BoardId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_connections_notes_board_id_target_note_id");

                    b.Navigation("SourceNote");

                    b.Navigation("TargetNote");
                });

            modelBuilder.Entity("Wukna.Features.Notes.Note", b =>
                {
                    b.HasOne("Wukna.Features.Board.Board", "Board")
                        .WithMany("Notes")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_boards_board_id");

                    b.HasOne("Wukna.Features.Notes.Note", "ParentNote")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("BoardId", "ParentNoteId")
                        .HasPrincipalKey("BoardId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_notes_notes_board_id_parent_note_id");

                    b.Navigation("Board");

                    b.Navigation("ParentNote");
                });

            modelBuilder.Entity("Wukna.Features.Notifications.TaskNotification", b =>
                {
                    b.HasOne("Wukna.Features.Tasks.PersonalTask", "Task")
                        .WithOne()
                        .HasForeignKey("Wukna.Features.Notifications.TaskNotification", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_notifications_personal_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Wukna.Features.Notifications.TaskReminder", b =>
                {
                    b.HasOne("Wukna.Features.Tasks.PersonalTask", "Task")
                        .WithOne()
                        .HasForeignKey("Wukna.Features.Notifications.TaskReminder", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_reminders_personal_tasks_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Wukna.Features.Tasks.PersonalTask", b =>
                {
                    b.HasOne("Wukna.Features.Tasks.PersonalTaskList", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_personal_tasks_personal_task_lists_list_id");

                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personal_tasks_users_user_id");

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Tasks.PersonalTaskList", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_personal_task_lists_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Tasks.PlanningSettings", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithOne()
                        .HasForeignKey("Wukna.Features.Tasks.PlanningSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_planning_settings_asp_net_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Tasks.TaskTemplate", b =>
                {
                    b.HasOne("Wukna.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_templates_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wukna.Features.Board.Board", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Wukna.Features.Chat.ChatMessage", b =>
                {
                    b.Navigation("Attachment");

                    b.Navigation("ScheduledTask");
                });

            modelBuilder.Entity("Wukna.Features.Notes.Note", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");
                });

            modelBuilder.Entity("Wukna.Features.Users.User", b =>
                {
                    b.Navigation("BoardMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
